language: rust
rust:
  - nightly

install:
  - cargo install xargo
  - rustup component add rust-src

before_script:
  - wget http://software-dl.ti.com/msp430/msp430_public_sw/mcu/msp430/MSPGCC/latest/exports/msp430-gcc-6.4.0.32_linux64.tar.bz2 -O /tmp/msp430-gcc.tar.b2
  - tar -xvjf /tmp/msp430-gcc.tar.b2
  - export PATH=$PATH:$PWD/msp430-gcc-6.4.0.32_linux64/bin

script:
  - make timer

cache: cargo
  directories:
    - $HOME/.xargo
before_cache:
  - chmod -R a+r $HOME/.cargo

branches:
  only:
    - master

notifications:
  email:
    on_success: never
