[package]
name = "at2xt"
version = "2.1.0"
authors = ["William D. Jones <thor0505@comcast.net>"]

[features]
use-timer = []

[dependencies.msp430]
version = "0.1.0"

[dependencies.bit_reverse]
version = "0.1.7"
default_features = false

[dependencies.msp430-rt]
git = "https://github.com/cr1901/msp430-rt"
branch = "termination"
features = ["abort-on-panic"]

[dependencies.msp430g2211]
git = "https://github.com/cr1901/msp430g2211"
branch = "termination"
features = ["rt"]

[dependencies.msp430-rtfm]
git = "https://github.com/cr1901/msp430-rtfm"
branch = "at2xt-pin"

[dependencies.msp430-atomic]
version = "0.1.0"

[profile.dev]
debug = true

[profile.release]
codegen-units = 1
incremental = false
lto = true
