[package]
name = "at2xt"
version = "2.0.0"
authors = ["William D. Jones <thor0505@comcast.net>"]

[dependencies.bit_reverse]
version = "0.1.7"
default_features = false

[dependencies.msp430-rt]
version = "0.1.0"
features = ["abort-on-panic"]

[dependencies.msp430g2211]
git = "https://github.com/cr1901/msp430g2211"
features = ["rt"]

[dependencies.msp430-rtfm]
git = "https://github.com/japaric/msp430-rtfm"
rev = "4b485e61a"

[dependencies.msp430-atomic]
git = "https://github.com/pftbest/msp430-atomic"

[profile.dev]
debug = true

[profile.release]
lto = true

[replace]
"https://github.com/japaric/rtfm-syntax#0.1.0" = { git = "https://github.com/japaric/rtfm-syntax", rev = "631e4b04"}
