[package]
# build = "build.rs"
name = "at2xt"
version = "1.3.0"
authors = ["William D. Jones <thor0505@comcast.net>"]
edition = "2018"

[dependencies]
volatile-register = "0.1.2"
bare-metal = "0.1.0"

[dependencies.bit_reverse]
version = "0.1.7"
default_features = false

[dependencies.msp430]
version = "0.1.0"

[dependencies.msp430-rt]
version = "0.1.0"

[dependencies.msp430g2211]
version = "0.1.0"
features = ["rt"]

[dependencies.panic-msp430]
version = "0.1.0"

[dependencies.msp430-atomic]
version = "0.1.0"

[features]
use-timer = []

[profile.dev]
debug = true

[profile.release]
lto = true
