[package]
name = "at2xt"
version = "2.2.0"
authors = ["William D. Jones <thor0505@comcast.net>"]

[features]
use-timer = []

[dependencies.msp430]
version = "0.1.0"

[dependencies.bit_reverse]
version = "0.1.7"
default_features = false

[dependencies.msp430-rt]
# Test that removed abort-on-panic feature still works.
git = "https://github.com/rust-embedded/msp430-rt"
rev = "a39c6c3"

[dependencies.msp430g2211]
version = "0.1.4"
features = ["rt"]

[dependencies.msp430-rtfm]
# RTFM has changed a lot, pin to old version for now.
git = "https://github.com/cr1901/msp430-rtfm"
branch = "at2xt-pin"

[dependencies.msp430-atomic]
version = "0.1.0"

[dependencies.panic-msp430]
version = "0.1.0"

[profile.dev]
debug = true

[profile.release]
codegen-units = 1
incremental = false
lto = true

[patch.crates-io]
# For MSP430G2211 crate for now.
msp430-rt = { git = "https://github.com/rust-embedded/msp430-rt", rev = "a39c6c3" }
