[package]
build = "build.rs"
name = "at2xt"
version = "1.1.0"
authors = ["William D. Jones <thor0505@comcast.net>"]

[dependencies]
volatile-register = "0.1.2"
bare-metal = "0.1.0"
r0 = "0.2.1"

[dependencies.bit_reverse]
version = "0.1.7"
default_features = false

[dependencies.msp430]
git = "https://github.com/pftbest/msp430"

[profile.dev]
debug = true

[profile.release]
lto = true
