[package]
name = "at2xt"
version = "2.0.0"
authors = ["William D. Jones <thor0505@comcast.net>"]

[dependencies.bit_reverse]
version = "0.1.7"
default_features = false

[dependencies.msp430-rt]
git = "https://github.com/pftbest/msp430-rt"
features = ["abort-on-panic"]
version = "0.1.0"

[dependencies.msp430g2211]
git = "https://github.com/cr1901/msp430g2211"
features = ["rt"]

[dependencies.msp430-rtfm]
git = "https://github.com/japaric/msp430-rtfm"

[profile.dev]
debug = true

[profile.release]
lto = true
